spring:
  application:
    name: nacos-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.18.44:8848
        weight: 1

server:
  port: 9001

management:
  endpoints:
    web:
      exposure:
        include: "*"